# ReCode by @indomiegenetik
# FROM Indomieuserbot <https://github.com/indomiegorengsatu/indomieuserbot>
# KONTOLLLLL MEMEEEK JEMBUUUT

from platform import uname
from userbot import ALIVE_NAME, CMD_HELP
from userbot.events import register

# ================= CONSTANT =================
DEFAULTUSER = str(ALIVE_NAME) if ALIVE_NAME else uname().node
# ============================================

# War anjing


@register(outgoing=True, pattern=r"^\.emak(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**PUNYA EMAK JANGAN JELEK GUE TAU EMAK LO UDAH MUKA JELEK ITEM BAT ITEM KEK OLI MOTOR BELOM DI GANTI SETAHUN HAHA TERUS BADANNYA GENDUT BAT GENDUT TETENYA KONDOR LAGI PANTESAN AJA KAGA LAKU HAHAHA NIH GUA KASIH TAU YE SAMA LO BOKAP LO AJE KERJAANNYA MAEN JUDI MULU BORO BORO MENANG BOKAP LO AJE MAEN JUDI KALAH MULU TOLOL HAHA UDAH NGUTANG SANA SINI AMPE DI KEJAR DEB COLLECTOR ITU BOKAP LO LAGI DI BURU OLEH DEP COLECTOR MANGKANYA KALO UDAH TAU MISKIN KERJAANNYA JANGAN MAEN JUDI MULU TOLOL SAMA NGUTANG CARI KERJA YANG HALAL SONO HAHA**"
    )

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern='^.ros(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**MUKA LU JELEK BEGITU TOLOL MUKA KAYAK TAPE BASI BELAGU LU KONTOK GUA KASIH TAU AJA BUAT LU BOCAH TOLOL BOCAH BOCAH KAYAK LU NI YANG SUKA MAIN DISAWAG NGEJAR NGEJAR LAYANGAN BEGITU SAMBIL MAIN LUMPUR LUMPURAN SAMPE MUKA LU ITEM BEGITU KAYAK ABIS MAGHRIB APALAGI LU MANDI MASIH DIKALI BEGITU SAMBIL NYUCI BAJU BARENG EMAK LU DIJEMUR DIATAS RUMAH LU YANG KECIL BEGITU TOLOK KARNA KELUARGA LU KELUARGA PALING MISKIN DALAM SEGALA HAL TOLOL KRNA KELUARGA LU SEMUANYA GAPUNYA PENDIDIKAN PANTESAN SUKA DIBEGO BEGOIN SAMA ORANG TOLOL APALAGI NI YAA KALO LAGI HUJAN ITU KESEMPATAN LU BUAT NGELUARIN EMBER BUAT NGAMBIL AIR HUJAN KARNA DIRUMAH LU GADA AIR LAGI BUAT MANDI TOLOL SABUN AJA UDH BOLONG BEGITU DIPAKEIN BAPALU COLI SAMPE JEMBUT NYA RONTOK BEGITU UDH KAYAK RAMBUT AJA TAPI KAN BAPALU BOTAK BEGITU YA GAPUNYA RAMBUT SAMA AHA OTAKNYA JUGA KOPONG KAYAK DENGKULNYA BAPALU UDH PUNYA ISTRI MSIH AJA DOYAN COLI TOLOL MUNGKIN KARNA MEMEK MAK LU UDH JEBOL GEDE BEGITU DITUSBOLIN PAKE PISO DAPUR YANG TAJEM BEGITU KAYAK KUKU BAPALU GADIPOTONG POTONG SAMPE TAJEM BEGITU UDH KAYAK JAMET PUNYA KUKU PANJANG PANJANG BIAR DIKATA JAGO KALI YA PADAHAL KAYAK ORANG IDIOT KUKU DIPANJANGIN KONTOL DIPANJANGIN BIAR PADA DOYAN TOLOL BILANGIN KEBAPALU LU TUH DONGO LU KALO JADI ANAK YANG BENER YANG NGELAWAN ORANG TUA TOLOL TIAP HARI BUKA TELE DISURUH BELI KECAP NOLAK MULU LU TOLOL ANAK GGUNA GATAU TERIMAKASIH DARI ORANG TUA LU TOLOL BIAR DIKATA KELUARGA LU KELUARGA MISKIN PENDIDIKAN MISKIN HARTA MISKIN SEMUANYA LU HARUS BERTERIMAKASIH SAMA BAPALU LU YANG GAGUNA ITU KONTOL BIAR KEDEPANNYA LU GA SESAT APALAGI LU HARUS BERTERIMAKASIH SAMA GUA KARNA BAPALU AJA MASIH DIBIAYAIN SAMA GUA BEGO Nyerocos LU MASIH Lama  GE TOLOL**")

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern=r"^\.ehh(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**EHH TOLOL PEKERJAAN KAKEK LO DULU ITU JADI BABU BABU KOMPENI YANG DI SURUH BIKININ KOPI TERUS MOTONG RUMPUT DI HALAMAN RUMAH YAELAH KASIAN BAT KASIAN KAKEK LO ITU UDAH KONTET KURUS KERING KEREMPENG LAGI KAKEK LO DULU MATINYA KE ABISAN TENAGA PAS NYABUTIN RUMPUT TOLOL HAHA NENEK LO JUGA JADI LACUR KOMPENI NENEK LO AJE JADI LACUR KOMPENI CUMA DI BAYAR PAKE SINGKONG REBUS DOANG SATU BIJI TERUS NENEK LO ITU MATINYA PAS DI GANGBANG SAMA TENTARA KOMPENI MEMEK NENEK LO ITU DI SODOK SODOK MAKE SENAPAN NOH SAMPE MEMEKNYA LOBEH LEBAR BAT LEBAR KEK JALAN RAYA HAHA.BADUR BADUT IYE GUE TAU LO MAIN TELE ITU DI JADIIN BADUT ALIANSI KAN HAHAHA MANGKANYA BANG KALO JADI ORANG PAS DI SENGGOL LAWAN JANGAN DIEM BAE KEK BATU HAHA DI JADIIN BADUT KAN LO DI LEDEK LEDEKIN SAMA SEMUA ALIANSI,GUE TAU TUJUAN LO MAEN TELE ITU UNTUK MENCARI MEMEK MEMEK SEGAR KAN HAHA KETAUAN ORANG ORANG KEK LO OTAK SANGEAN YANG HAUS AKAN MEMEK DAN TOKET SAKING GK MAU MODAL DI RL BUAT NYEWA LACUR JADI LO MEMILIH BIAT MAIN TELE BORO BORO DAPET LAH LU KAGA DAPET SAMA SEKALI MANGKANYA GANTENG KONTOL LO UDAH JELEK PENGENNYA YANG BAGUS BAGUS NYADAR DIRI LO ITU UDAH JELEK TERUS MISKIN LAGI**"
    )

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern='^.rst(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**⁪⁬EHH DASARR BOCAH GELAS PECAH KEPALA KOTAK KAYAK SEMPAK YANG DI BUANG KESAMPAH**")
    sleep(4)
    await typew.edit("**DASAR KAU SETAN ALAS MUKA KAYAK TERAS BANTAL BUSUK OTAK SEMPIT KAYAK LUBANG ANUS KUTENDANG KAU LANGSUNG PINCANG KU GAMPAR KAU KESURUPAN KUCIDORII KAU LANGSUNG KEJANG KEJANG KUHANTAM MUKA KAU BONYOK KAYAK PEMANJANG JEMBUT WAK DOYOK**")
    sleep(4)
    await typew.edit("**EHH DASAR KELUARGA KERTAS MATA BESAR KAYAK MATA CYCLOPS KU SENIPER KEPALA KAU HANCUR MUKA ROBEX KAYAK SOFTEX AYU TING TING KU SLEDING MALAH BUNTING TOLOL JANCOK**")
    sleep(4)
    await typew.edit("**BOCAH SUPERMEN MERANGKAK KULIT HIJAU KAYAK HULUK KURUS KERING NGOCOK PAKAI MESIN CUCI KU TONJOK MALAH BERUBAH JADI POWER RENJER**")

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern='^.wr(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**EH KONTOL GUA KASIH TAU NIH YAA, BOCAH BOCAH KAYA LU MAH KAGA PANTES PISAN MAIN DI TELE, KARNA APA? JARI JARI TANGAN LU AJA ITU PADA BUNTUNG BEGO, BIBIR LU JUGA SUMBING BEGITU, GUA TAU NIH YAA PAS MASIH DI DALEM KANDUNGAN, LU TUH GAK BISA DIEM KAN, MANGKANYA LU JADI BEGINI, CACAT BET CACAT, GUA MAH KASIAN SAMA LU, PAS MASIH BAYI JUGA LU KAGA DI KASIH AIR ASI KAN, EMANG LU PANTES DAPET BEGITU, DI KASIH AIR COMBERAN JADI OTAKNYA DONGO BEGINI NIH, LAGIAN JUGA YAA MAUPUN LU DI LAHIRIN DENGAN SEMPURNA LU JUGA GAK GUNA, KARNA APA, LU EMANG UDAH GAK PANTES TINGGAL DI BUMI ANJINGGG, LU TUH PANTESNYA TINGGAL DI DALEM BUMI GITU TUH, SENDIRIAN GAK PUNYA TEMEN, JADI ORANG GAK BERGUNA, LAGIAN JUGA KALO LU TINGGAL DI BUMI, LU TUH GAK PANTES DAN GAK COCOK, KARNA APA, KARNA LU TUH SEMUA SERBA KEKURANGAN, LU MAU TINGGAL DI LUAR ANGKASA JUGA GUA YAKIN ALIEN KAGA MAU TERIMA LU, KARNA LU TUH GAK SESUAI KRETERIA MEREKA, LU TUH JELEK BET JELEK, LEBIH JELEK DARI PADA MUKA KECOA, BISA SIH LU TINGGAL DI LUAR ANGKASA, ITU JUGA PALING JAUH, JAUH DARI PERADABAN HAHAHA, KARNA TEMPAT TEMPAT BEGITU EMANG COCOK BUAT LU, KALO DI PIKIR PIKIR OTAK SEMUT SAMA OTAK LU JUGA GUA RASA PINTERAN OTAK SEMUT GITU, KARNA APA, LU TUH DONGO NYA JELAS BANGET, SAMPE KE TULANG TULANG, KE BOOL BOOL, KE SEL SEL DARAH LU IKUTAN BLOON HAHAHAHA**")

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern='^.ro(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("**EH ANJING GW KASIH LIAT KOSA KATA YANG BERDAMAGE**")
    sleep(2)
    await typew.edit("**LIAT KOSA KATA LO YANG UDAH BASI TOLOL YANG BANYAK DI PAKE ORANG SAMA KAYA EMAK LO YANG SERING DI PAKAI ORANG TOLOL, MAK NYA UDAH KAYA ROKOK SATU BATANG BISA DI PAKE RAME RAME YAKAN ITU MAK LO TOLOL KASIAN DIA JAM SEGINI BELOM PULANG KARENA MASI CARI UANG PAKAI MEMEK NYA YANG UDAH BECEK ITU TOLOL APA LO KAGA KASIAN BEGO LIAT MAK LO YANG KEK GITU MENDINH MAMAK LO SURUH KERJA YANG BENER TOLOL JANGAN NGELONTE MULU, KASIAN JUGA LIAT BAPAK LO BAU TANAH YHAHAHAHA**")

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern=r"^\.mas(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**MAS KALO UDA NGANTUK BOBO AJA JANGAN MAKSAIN TERUS BUAT LAWAN GUA TAKUTNYA LO BESOK KENA ANGIN DUDUK DOANG TERUS MATI DAH KAN KASIAN UDAH JADI BEBAN KELUARGA MALAH NAMBAHIN BEBAN TOLOL. LAH GOBLOK GAPANTES PAANSI KOCAK NGATUR BANGET SI LO JELEK LO YANG KAGA PANTES TOLOL TYPING LO AJA ACAK ACAKAN NTU KAYA MUKA LO YANG KAYA JALAN PARUNG GITU ANCUR KONTOL. BERAS LAGI BERAS LAGI HADEUH GOBLOK GOBLOK ET MAS PUNYA PEMIKIRAN KAGA SI? ET IYA LUPA OTAK BE ORA ADA APALAGI PEMIKIRAN YA WKWK GOBLOK. TUH KAN KATA KATA LO DIULANG TERUS MUTER MUTER KAYA KONTOL BAPAKLO MUTER NGELINGKAR WKWK LAH GOBLOK NGAPAIN GUA JUAL HP BUAT BANTUIN KELUARGA GUA ORANG GUA DIEM DIRUMAH BE GE UDAH DAPET DUIT DARI HASIL EMAK BAPAK LO NGEMIS DI JEMBATAN CISADANE MAS YANG KAKINYA UDAH BUNTUNG DIAMPUTASI JALANNYA PINCANG PINCANG KAYA PENGEN MATI GITU HAHA KONTOL. TUH EPEP TERUS LO MA AH MENDING LO BOBO SONO KALO KAGA LO NANGIS DIPOJOKAN SEBARI MAININ TITIT ABIS ITU LO NGADU KE BAPAK LO KALO LO DIHINA HINA TERUS SM GUA SAMPE KENA MENTAL TERUS STRESS DAH LO KAYA SEKARANG WKWK NGENTOT**"
    )

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern=r"^\.dih(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**DIHHH NAJISS ANAK HARAM LO GOBLOK, JANGAN BELAGU DIMARI KAGA KEREN LU KEK BGITU KONTOL!**"
    )


@register(outgoing=True, pattern=r"^\.gcs(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**GC SAMPAH KAYA GINI, BUBARIN AJA GOBLOK!!**"
                     )

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern=r"^\.skb(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**EMANG KITA KENAL? KAGA GOBLOK SOKAB BANGET LU GOBLOK**"
                     )

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern=r"^\.an(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**LO KAN HASIL ZINAH HASIL HUB TERLARANG NAH LO DI BUANG DI TONGSAMPAH NAH MAK LO YG SKRG KASIAN SAMA LO MKNY DI PUNGUT UDH LO CACAT KAKI CACAT TANGAN CACAT MUKA CACAT SEMUAHNY PARAH BET SI KONTOL LO JUGA CACATAN PASTI NANAHAN JUGA,UDH MENDING LO BUNDIR DEH JADI BEBAN ORG DOANG BEGO NGERUGIN MASYARKAT BEGO BOCAH HINA BOCAH HARAM BOCAH AUTIS KEK LO MENDING MATI AJA**"
    )

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern=r"^\.bk(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**BUAT LO KONTOL NIH KALO UDAH HINA GAUSAH SOK SOK NGEHINA HINA GUA KONTOL, GUA TERLALU SUCI BUAT LU YANG HINA ITU ADUHHH. SINI GUA LUDAHIN DLU LU BIAR DIRI LU SUCI KARENA LU TAU LUDAH GUA ITU MULIA SEKALI**"
    )

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern=r"^\.gj(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**YA AMPUN LU NGOMONG APA? GA NYAMBUNG KONTOL KAYA KEHIDUPAN LU MAKANYA ORG ORG KAYA LU GABAKALN MAJU HIDUPNYA APA LAGI ORG ORG BAWAHAN KAYA LU.**"
    )

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern=r"^\.gh(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**DUH GINI NIH BOCAH YG LAHIR DI GUBUK BAMBU REOT + GAPUNYA HARGA DIRI, PADAHAL MAH DARI KECIL DIAJARIN SM EMAKNYA GABOLEH SONGONG SM MAJIKAN MASIH AJA SONGONG, MENDING LO URUSIN DULU GOBLOK KELUARGA LO YG PENYAKITAN ITU, MANA BAPA LO KAKINYA BOROK BEGITU AJG BERNANAH BAU AMIS IDIH GELI BET GELI GUA LIATNYA, NAH SEKALIAN TUH URUSIN JUGA ADE LO TUH, KALO BUKAN KARENA GUA MAH ADE LO UDAH MENINGGAL KENA TUMOR TOLOL MAKANYA LO KUDU SUJUD DEPAN GUA YAKAN,EMAK LO JUGA TUH JAGAIN UDAH BISU BEGITU YAKAN TAKUTNYA JATOH GABISA TREAK, MAKANYA NIH YA JANGAN KEBANYAKAN KONSUMSI SASA MICIN GOBLOK LIAT KAN EFEKNYA LO JADI KEK BOCAH AYAN BEGITU, SAMPE² LO BERANI GITU YAKAN NYENGGET JEMURAN ORANG SAMPE LO DIPUKULIN TRUS DI INJEK² SAMA WARGA SEKAMPUNGAN, GINI YA GUA KASIH TAU NIH SAMA LO NIH KALO UDA MISKIN KAGA USAH BELAGU SEGALA TOLOL, MIKIR LO MAKAN AJA SUSAH SAMPE NGEMIS² DI KOMPLEK PERUMAHAN GUA SAMPE DI USIR SAMA SATPAM KOMPLEK GUA, BERAS AJA LO BOLEH DIBAGI SAMA EMAK GUA YAKAN LAUK PAUK IKAN, AYAM, DAGING SEGALA RUPA AJA LO BOLEH NYOLONG DARI PASAR BOCAH KAYA LO MAH GIZINYA KURANG DONGO SABAN HARI MAKAN INDOMI 1 PAKE TELOR DOANG ITU JUGA JOINAN SM KELUARGA LU, KARENA APA?, YA KARENA LO MISKIN GA MAMPU BELI MAKANAN YG BERGIZI, DIKASIH KUAH SAYUR KANGKUNG JUGA MAO TOLOL ITU JUGA UDAH BERSYUKUR BISA MAKAN MAKANAN SELAEN MI INSTAN YAKAN SECARA LO GABISA GITU KEK GUA YAKAN MAKAN APA YG GUA MAO LAH ELO MAKAN MAKANAN TONG SAMPAH JUGA UDAH ALHAMDULILLAH BANGET AJG**"
    )

# indomie cakep bngtz sumph !


@register(outgoing=True, pattern=r"^\.lol(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**TALAL TOLOL TALAL TOLOL KEK ORG DONGO, NIH YA DENGERIN MAKANYA BESOK² JANGAN NGELEM MULU OTAK LO, JADI LEMBEK DAH TUH PALA, MANA SABAN HARI MAKE SAMPO SACHET YG SEREBUAN GIMANA GA KETOMBEAN TU PALA, YA JELAS LAH BEDA SAMA GUA YA GUA SI PAKE SAMPO BOTOLAN GITU YAKAN, MANA SABUN BETAK DI RUMAH ORANG BEKAS COLI JUGA DIPAKE SAMA KELUARGA LO BUAT MANDI YA KARENA APA?, KARNA KELUARGA LO TUH HINA TOLOL BAHKAN LEBIH HINA DARIPADA HEWAN, LO KAGA PANTES MAEN TELE SUMPAH MENDING LO SEKOLAH DULU DAH YG BENER DI BIAYAIN AMA PEMERINTAH AJA GATAU DIRI KONTOL, LO PIKIR BAPA EMAK LO MAMPU GITU BIAYAIN LO SEKOLAH?, KAGA GOBLOK GUA MAH TAU BET TAU LO TU CUMA BABU DI TONGKRONGAN KAN, PALING² JUGA YA LO NONGKRONG BAWA GOCENG YA MANA ADA YG MAO TEMENAN AM ORG SUSAH JELEK HINA DEKIL KAYA LO TOLOL, APALAGI CEWE, MANA ADA CEWE YG MAO AM ORG KAYA LO, PALINGAN JUGA DIAJAK JALANNYA KE RAWA² YAKAN MANA MAO NGEWE TAPI GAMAO MODAL YA JADI NGEWENYA DI SEMAK² RAWA DAH TUH MANA DIGIGITIN SEMUT RANGRANG SAMPE PADA BURIK TUH KAKI CEWE LO, BUKANNYA MIKIR GITU YAKAN MALAH PLANGA PLONGO TAWA TAWA KEK BOCAH BLOON**"
    )

# indomie cakep bngtz sumph !

CMD_HELP.update(
    {
        "war2": "𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .ehh\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .emak\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .ros\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .rst\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .wr\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .ro\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .mas\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .dih\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .gcs\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .skb\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .an\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .bk\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .gj\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .gh\
        \n↳ : lihat sendiri\
        \n𝘾𝙤𝙢𝙢𝙖𝙣𝙙: .lol\
        \n↳ : lihat sendiri\
        \n↳ **COBAIN AJA SENDIRI SEMUA!**.\
    "
    }
)
